name: CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: CI-${{ github.ref }}
  # Queue on all branches and tags, but only cancel overlapping PR burns.
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
jobs:
  org-check:
    name: Check GitHub Organization
    if: github.repository_owner == 'jsirois'
    runs-on: ubuntu-24.04
    steps:
      - name: Noop
        run: "true"
  checks:
    name: "${{ matrix.os }} Python ${{ matrix.python-version }}: uv run dev-cmd ci"
    needs: org-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            python-version: "3.8"
          - os: ubuntu-24.04
            python-version: "3.9"
          - os: ubuntu-24.04
            python-version: "3.10"
          - os: ubuntu-24.04
            python-version: "3.11"
          - os: ubuntu-24.04
            python-version: "3.12"
          - os: ubuntu-24.04
            python-version: "3.13"

          - os: macos-15
            python-version: "3.13"

          - os: windows-2022
            python-version: "3.13"
    steps:
      - name: Checkout dev-cmd
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run CI checks
        run: uv run dev-cmd --color always ci -- -vvs

